# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='foo.proto',
  package='foo',
  syntax='proto3',
  serialized_options=_b('\n\003foo'),
  serialized_pb=_b('\n\tfoo.proto\x12\x03\x66oo\"N\n\x03\x42\x61r\x12\x15\n\x01x\x18\x01 \x03(\x0b\x32\n.foo.Bar.X\x1a\x30\n\x01X\x12\x17\n\x01y\x18\x01 \x03(\x0b\x32\x0c.foo.Bar.X.Y\x1a\x12\n\x01Y\x12\r\n\x05value\x18\x01 \x01(\x04\"\x1c\n\x03\x46oo\x12\x15\n\x03\x62\x61r\x18\x01 \x03(\x0b\x32\x08.foo.BarB\x05\n\x03\x66oob\x06proto3')
)




_BAR_X_Y = _descriptor.Descriptor(
  name='Y',
  full_name='foo.Bar.X.Y',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='foo.Bar.X.Y.value', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=96,
)

_BAR_X = _descriptor.Descriptor(
  name='X',
  full_name='foo.Bar.X',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='y', full_name='foo.Bar.X.y', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_BAR_X_Y, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=96,
)

_BAR = _descriptor.Descriptor(
  name='Bar',
  full_name='foo.Bar',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='foo.Bar.x', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_BAR_X, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=96,
)


_FOO = _descriptor.Descriptor(
  name='Foo',
  full_name='foo.Foo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bar', full_name='foo.Foo.bar', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=126,
)

_BAR_X_Y.containing_type = _BAR_X
_BAR_X.fields_by_name['y'].message_type = _BAR_X_Y
_BAR_X.containing_type = _BAR
_BAR.fields_by_name['x'].message_type = _BAR_X
_FOO.fields_by_name['bar'].message_type = _BAR
DESCRIPTOR.message_types_by_name['Bar'] = _BAR
DESCRIPTOR.message_types_by_name['Foo'] = _FOO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Bar = _reflection.GeneratedProtocolMessageType('Bar', (_message.Message,), dict(

  X = _reflection.GeneratedProtocolMessageType('X', (_message.Message,), dict(

    Y = _reflection.GeneratedProtocolMessageType('Y', (_message.Message,), dict(
      DESCRIPTOR = _BAR_X_Y,
      __module__ = 'foo_pb2'
      # @@protoc_insertion_point(class_scope:foo.Bar.X.Y)
      ))
    ,
    DESCRIPTOR = _BAR_X,
    __module__ = 'foo_pb2'
    # @@protoc_insertion_point(class_scope:foo.Bar.X)
    ))
  ,
  DESCRIPTOR = _BAR,
  __module__ = 'foo_pb2'
  # @@protoc_insertion_point(class_scope:foo.Bar)
  ))
_sym_db.RegisterMessage(Bar)
_sym_db.RegisterMessage(Bar.X)
_sym_db.RegisterMessage(Bar.X.Y)

Foo = _reflection.GeneratedProtocolMessageType('Foo', (_message.Message,), dict(
  DESCRIPTOR = _FOO,
  __module__ = 'foo_pb2'
  # @@protoc_insertion_point(class_scope:foo.Foo)
  ))
_sym_db.RegisterMessage(Foo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
