[project]
name = "proto-leak"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "grpcio-tools>=1.76.0",
    "protobuf>=6.33.0",
    "psutil>=7.1.2",
    "psutils>=3.3.14",
]
