# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='schema.proto',
  package='com.mycorp.mynamespace',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cschema.proto\x12\x16\x63om.mycorp.mynamespace\"H\n\x10value_test_topic\x12\x10\n\x08myField1\x18\x01 \x01(\x05\x12\x10\n\x08myField2\x18\x02 \x01(\x01\x12\x10\n\x08myField3\x18\x03 \x01(\tb\x06proto3'
)




_VALUE_TEST_TOPIC = _descriptor.Descriptor(
  name='value_test_topic',
  full_name='com.mycorp.mynamespace.value_test_topic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='myField1', full_name='com.mycorp.mynamespace.value_test_topic.myField1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='myField2', full_name='com.mycorp.mynamespace.value_test_topic.myField2', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='myField3', full_name='com.mycorp.mynamespace.value_test_topic.myField3', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=112,
)

DESCRIPTOR.message_types_by_name['value_test_topic'] = _VALUE_TEST_TOPIC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

value_test_topic = _reflection.GeneratedProtocolMessageType('value_test_topic', (_message.Message,), {
  'DESCRIPTOR' : _VALUE_TEST_TOPIC,
  '__module__' : 'schema_pb2'
  # @@protoc_insertion_point(class_scope:com.mycorp.mynamespace.value_test_topic)
  })
_sym_db.RegisterMessage(value_test_topic)


# @@protoc_insertion_point(module_scope)
